### ISSUE TITLE
Couldn't find truststore error

### ISSUE THREAD

**Issue by JoseClua** [AuDigitalHealth/hi-b2b-client-java#1]
Hi,

Here's some context for our problem:

- We are developing a MuleSoft API that connects to HI.
- We have received the certificates (p12 files - we generate jks files from it) and PCIN details.
- I was able to **successfully send a request using sample .net code** (which means the certificates are valid).
- With the MuleSoft OOTB Web Service Consumer connector, I always get this error:

`Signature signer format not supported or not recognized in message. (from the client)`

- We tried all possible variation in the connection signature configuration.
- As an alternative, we can use this java code within the MuleSoft API since MuleSoft has a Java connector.
- I added all the pom dependencies in the MuleSoft pom file and the project is building fine.
- I also added the metro-project v2.3.1 dependency in the MuleSoft pom file.
- I'm trying to invoke the main method of the ConsumerSearchIHIClientSample class.
- I added our keystore.jks and truststore.jks to the mulesoft main/resources folder.
- I configured the properties below:
```
PRODUCT_NAME = "xyd";
PRODUCT_VERSION = "1.0";
VENDOR_QUALIFIER_ID = "wyz";
VENDOR_QUALIFIER = "http://ns.electronichealth.net.au/id/hi/vendorid/1.0";
USER_QUALIFIED_ID = "HIClient-1";
USER_QUALIFIER = "http://ns.electronichealth.net.au/hi/xsd/common/QualifiedIdentifier/3.0";
PRIVATE_KEY_STORE_TYPE = "JKS";
PRIVATE_KEY_STORE_PASSWORD = "xyz";
PRIVATE_KEY_STORE_FILE = "keystore.jks";
PRIVATE_KEY_ALIAS_NAME = "xyz";
PRIVATE_KEY_CERTIFICATE_ALIAS_NAME = "xyz";
TRUSTSTORE_TYPE = "JKS";
PRIVATE_KEY_PASSWORD = "xyz";
TRUSTSTORE_FILE = "truststore.jks";
TRUSTSTORE_PASSWORD = "xyz";
MEDICARE_ENDPOINT_URL = "https://www5.medicareaustralia.gov.au/cert/soap/services/";
INDIVIDUAL_IHI_NUMBER = "http://ns.electronichealth.net.au/id/hi/ihi/1.0/xyz";
INDIVIDUAL_FAMILY_NAME = "xyz";
INDIVIDUAL_GIVEN_NAME = "xyz";
private static final XMLGregorianCalendar INDIVIDUAL_DATE_OF_BIRTH = TimeUtility.getXMLGregorianDate("19780505");
private static final SexType GENDER = SexType.M;
```
However, when the code gets in this function:
```
private static X509Certificate getSigningCertificate() throws GeneralSecurityException {
        X509Certificate clientSigningCertificate = KeystoreUtil.getSigningCertificate(PRIVATE_KEY_STORE_TYPE,
                PRIVATE_KEY_STORE_PASSWORD, PRIVATE_KEY_STORE_FILE, PRIVATE_KEY_CERTIFICATE_ALIAS_NAME);

        return clientSigningCertificate;
    }
```
It fails and throws this error message:
```
"Invocation of static Method 'main(java.lang.String[])' from Class 'au.gov.nehta.vendorlibrary.hi.sample.ConsumerSearchIHIClientSample' with arguments [java.util.ArrayList<?> args] resulted in an error.
Expected arguments are [java.lang.String[] args].
Cause: java.security.GeneralSecurityException - Couldn't find truststore keystore.jks [Not accessible. Value obtained from method: getDetailedDescription()]"
```
This error is happening in au.gov.nehta.vendorlibrary.common.security, so I cannot see the source code for it and I don't know how the file is being picked up.
I suspect the issue might be realted to the fact that, since we are using MuleSoft, the build process is a little different and I am not setting all the properties in build.properties files. I've tried setting the resurce.dir in our runtime but that didn't help.

1. How it that library picking up the file? 
2. Is that library code available in github?
3. Do the libraries rely on the build.properties?
4. Do we need both the keystore and truststore?

Your help would be greatly appreciated!
Please see the attached file for the complete log.
Thanks,

Jose
[full.log](https://github.com/user-attachments/files/16776346/full.log)

**Comment by JoseClua** [comment]
I was able to fix this now I am getting this error:

"Invocation of static Method 'main(java.lang.String[])' from Class 'au.gov.nehta.vendorlibrary.hi.sample.ConsumerSearchIHIClientSample' with arguments [java.util.ArrayList<?> args] resulted in an error.
Expected arguments are [java.lang.String[] args].
Cause: javax.xml.ws.WebServiceException - Provider com.sun.xml.internal.ws.spi.ProviderImpl not found [Not accessible. Value obtained from method: getDetailedDescription()]"

**Comment by adha-admin** [comment]
Hi Josa,
Thanks for your feedback. 
If you can log a ticket through help@digitalhealth.gov.au, this will make it easier for me to respond to you directly.
I probably need to update our Readme.md  and CONTRIBUTING.md to recommendhow to contact us.
Cheers
Philip Wilford

**Comment by adha-admin** [comment]
Hi Jose, Did you get it sorted?

**Comment by JoseClua** [comment]
Hi, thanks for following up. The request did not work with the MuleSoft OOTB Web consumer connector. It fails to properly sign the request. I've tried every possible configuration. However, we managed to make it work using a MuleSoft Java connector where, basically, we used the same code found here in this sample.

**Comment by JoseClua** [comment]
we managed to make it work using a MuleSoft Java connector where, basically, we used the same code found here in this sample
